# Generated by Django 3.2 on 2023-01-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email_address', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=20)),
                ('plan_type', models.CharField(choices=[('Gym', 'Gym'), ('Home', 'Home'), ('Outdoor', 'Outdoor')], default='Gym', max_length=40)),
            ],
        ),
    ]
