# Generated by Django 3.2 on 2023-01-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='your_goal',
            field=models.TextField(default='', max_length=254),
        ),
    ]
